//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int id { get; set; }
        [Display(Name = "Customer Name")]
        [Required(ErrorMessage = "This field is required")]
        [RegularExpression(@"^((A - za - z]+[\s]{1}[A - za - z]+)|([A - za - z]+))$",ErrorMessage="Please Enter Upper and Lower case alphabets only")]
        public string CustName { get; set; }
        [Display(Name = "Address")]
        [Required(ErrorMessage = "This field is required")]

        public string Address { get; set; }

        [Display(Name = "Mobile")]
        [Required(ErrorMessage = "This field is required")]
        [RegularExpression(@"^[0][1-9]{10}$",ErrorMessage ="Please Enter correct Mobile Number")]
        public int Mobile { get; set; }
    }
}
