//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int id { get; set; }
        public string CarId { get; set; }
        public int CustId { get; set; }
        public int Fee { get; set; }
        public System.DateTime sDate { get; set; }
        public System.DateTime eDate { get; set; }
    }
}
