//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class returncar
    {
        public int id { get; set; }
        public string CarNo { get; set; }
        public int CustId { get; set; }
        public System.DateTime date { get; set; }
        public int elsp { get; set; }
        public int fine { get; set; }
    }
}
